### ISSUE TITLE
It seems it only can run for 1 hour 

### ISSUE THREAD

**Issue by Huijun-Cui** [sveneisenschmidt/selenium-server-standalone#45]
4%|▍         | 10111/236736 [58:09<411:23:14,  6.54s/it][]

  4%|▍         | 10112/236736 [58:19<469:56:24,  7.47s/it][]

  4%|▍         | 10113/236736 [58:28<507:13:25,  8.06s/it][]

  4%|▍         | 10114/236736 [58:38<532:35:46,  8.46s/it][]

  4%|▍         | 10115/236736 [58:47<553:07:19,  8.79s/it][]

  4%|▍         | 10116/236736 [58:57<565:48:53,  8.99s/it][]

  4%|▍         | 10117/236736 [59:06<574:09:36,  9.12s/it][]

  4%|▍         | 10118/236736 [59:32<895:22:20, 14.22s/it][]

  4%|▍         | 10119/236736 [59:51<974:46:02, 15.48s/it][]

  4%|▍         | 10120/236736 [1:00:00<859:20:54, 13.65s/it][]

  4%|▍         | 10121/236736 [1:00:37<1302:20:14, 20.69s/it]Traceback (most recent call last):
  File "main.py", line 50, in <module>
    html_pos_data = browser.find_element_by_xpath("//*").get_attribute("outerHTML")
  File "/home/v-hucu/anaconda3/envs/VerbParsing/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 143, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/home/v-hucu/anaconda3/envs/VerbParsing/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/v-hucu/anaconda3/envs/VerbParsing/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/v-hucu/anaconda3/envs/VerbParsing/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: GC overhead limit exceeded
Stacktrace:
    at java.util.Arrays.copyOf (Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append (StringBuilder.java:136)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1047)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printChildren (Element.java:1009)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.printNode (Element.java:1057)
    at com.gargoylesoftware.htmlunit.javascript.host.Element.getOuterHTML (Element.java:951)
    at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement.getOuterHTML (HTMLElement.java:632)
    at sun.reflect.GeneratedMethodAccessor139.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)

**Comment by asgrim** [comment]
Not sure if this is anything to do with this package; are you actually using PHP at all (looks like Python), as this is a Composer PHP package for bundling Selenium into PHP projects... Perhaps try https://github.com/SeleniumHQ/selenium or with whichever bindings/library you're using in Python... thanks!
